### ISSUE TITLE
User should be able to claim on the second day.

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodContracts#102]
New & inactive users claim

- Inactive user that claims is only activated in next epoch and start claiming only in next epoch (user is added to nextDayDistributionList)
- Distribute on next epoch the daily UBI automatically to users in the nextDayDistributionList - triggered by external service, in batches of 100, depending on block gas)
- On the second day users will accept 2 shares of that day. 
- Calculation of share:
- Total Amount/(Active users + previous day activated)
- Users can get the second share only for performing claim action on that day.

**Comment by sirpy** [comment]
removed in favour of #111
