### ISSUE TITLE
UBIScheme improvements

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodContracts#103]
Open separate issue for large tasks
1. AlreadyClaimed event - not required
2. Try to make all modifications before any token.transfer (avoid risk of reentrancy)
3.         require(isRegistered(account) && !isActiveUser(account), "is not an inactive user"); - isRegistered is redundnat already tested in isActiveUser
4. distribute - use array to keep list of pending users, input receive start index and end index
5. fishMulti, check address passes require conditions before calling fish

**Comment by ordd** [comment]
3 - the user might be registered but not active

**Comment by sirpy** [comment]
@ordd 
3. ok 
1. please remove

please connect the relevant PR to this issue 
open PR in zenhub and at the bottom connect it or mention in comments

**Comment by ordd** [comment]
@sirpy 
1. removed
