### ISSUE TITLE
Mint interest and ubi should only be callable once per 24 hours

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodContracts#107]
expansion can only be done once per 24hours
fundmanager collection can be triggered by anyone so ensure in reserve that minting/expansion can only happen once per 24 hours. probably should return zeros to fundmanager if called before.
we can also add condition in fundmanager that collection can happen only once per 24 hours

did we have anything else in the specs besides claiming that is 24hours based?

**Comment by ordd** [comment]
@sirpy staking contract - by blocks
