### ISSUE TITLE
Activated claimers should get claim from bonus pool

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodContracts#111]
1. Add smart contract FirstClaimPool, implements FeeLess scheme
2. can be destroyed and all GD/eth goes back to avatar, owner is Avatar
3.  constructor inputs: UBIScheme , claimAmount
4. methods: 
    - setUBIScheme onlyOwner
    - setClaimAmount onlyOwner
    - awardUser onlyUBIScheme - transfer claimAmount to address if balance>claimAmount and returns claimAmount otherwise doesnt transfer and returns 0
5. in UBIScheme when user becomes active instead of being added to the distribution pool he is awarded from the first claim pool by calling awardUser(address)
UBIScheme emits UBIClaimed event with flag activated=true even if amount from awardUser is 0
6. in UBIScheme add missing checkEntitlement (see old FixedUBI)
    - if user is inactive or not whitelisted return claimAmount from FirstClaimPool
    - otherwise return the daily calculated UBI amount
```
 /* @dev Checks amount address is eligible to claim for, regardless if they have been
     * whitelisted or not. If they have not been whitelisted, they are eligible to claim from FirstClaimPool.
     * @return The amount of GoodDollar the address can claim.
     */
    function checkEntitlement() public view requireActive returns (uint256) {
        ```

**Comment by ordd** [comment]
@sirpy 
6. in case claim or fish haven't executed at the current day and the user is active, then the daily amount ain't correct. optional solution: throw if the current day has not set yet.

**Comment by sirpy** [comment]
@ordd no this is just a view function. if day was not set then return a view of the calculation. ie pool/active

**Comment by ordd** [comment]
ok
