### ISSUE TITLE
Write SignupBonus scheme according to spec

### ISSUE THREAD

**Issue by Maasdamind** [GoodDollar/GoodContracts#12]
Spec is described as:

SignupBonus - We have an invitation model that you not only receive GD for joining but also for inviting and different tasks. This should be defined with a maxBonus = the maximum amount of awards a user can get and a method awardUser(amount) that can be called only by GoodDollar's own admin account. the awardUser then awards him with the amount and keeps an accumulator how much the user was awarded so far. if the amount+awardedSoFar>maxBonus then the method fails

**Comment by sirpy** [comment]
1. switch from minting to allow it to work on sidechain
2. release funds back to avatar when scheme ends
