### ISSUE TITLE
Get to 100% coverage

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodContracts#144]
- [x] list complicated cases here
- [x] add the simple test cases

**Comment by sirpy** [comment]
@ordd please list the uncoverred cases

**Comment by ordd** [comment]
ContributionCalculation.sol
-
calculateContribution - negative for the require _done_

FirstClaimPool.sol
-
end - remainingGDReserve <= 0 _done_
awardUser - modifiers _done_

GoodFundManager.sol
-
**transferInterest - inner conditions. need to add more cases at 138, 149, 151.  mock**

GoodMarketMaker.sol
-
buyReturn - modifier _done_
sellReturn - modifier _done_
sellWithContribution - modifiers, requires _done_
**currentPrice - modifiers**
mintInterest - modifier not owner _done_
**calculateMintInterest - modifier**
**calculateMintExpansion - modifier**
mintExpansion - nodifier not owner _done_

GoodReserveCDai.sol
-
**buy - failed transferFrom, not cdai 203 use mock**
**sell - failed transfer, not cdai 249 mock**
**mintInterestAndUBI - condition toMint = 0 296**
end - remainingReserve = 0 _done_

SimpleDAIStaking.sol
-
**stakeDAI - failed cdai minting 95-97 mock**
**redeemUnderlying - fail 117 mock**
