### ISSUE TITLE
Create guide for production deployment

### ISSUE THREAD

**Issue by Maasdamind** [GoodDollar/GoodContracts#15]
1. What should be deployed on mainnet
2. How to initially fund the UBI+rewards from mainnet to sidechain
3. Best practices for different keys and roles
4. Upgrading: general guide for upgrading different parts of the system
  - What contracts can be upgraded and how
  - who has permissions for that
  - syncing upgrades between mainnet and sidechain

**Comment by sirpy** [comment]
@Maasdamind 
I dont think the current guide answers the definition of the ticket
