### ISSUE TITLE
update model image on github README

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodContracts#157]
- [ ] the image from the specs shows TRX
- [x] it shows G$ interest goes back to stakers, maybe we want to show it go back to the Fund?

https://docs.google.com/document/d/192YY2z0HVenCShUZtiM_GNvoftjXs7xULYtH-Jq-AD8/edit#heading=h.9etwnu4nlexu

**Comment by tomerGD** [comment]
don't change the image money flow, only text

**Comment by LiavGut** [comment]
@sirpy 
![FC1@2x](https://user-images.githubusercontent.com/54103946/85539215-46b89f00-b61e-11ea-8f0a-eefc95ab5d58.jpg)
