### ISSUE TITLE
Extract SimpleDAIStaking into an abstract contract AbstractGoodStaking

### ISSUE THREAD

**Issue by reemaSomish** [GoodDollar/GoodContracts#160]
Details :

1. - [x] Create interface AbstractGoodStaking with all functions, data and event declarations for Staking Contract.
2. - [x]  The following functions need to be added to this interface
         - stake
         - withdrawStake
         - currentERC20Worth
         - currentUBIInterest
        - collectUBIInterest

**Comment by PremSOMISH** [comment]
Task is completed by my side but yet to be pushed into git.

**Comment by PremSOMISH** [comment]
Pushed above task into git. 

commit id: 01558a4fd9090ce06516c5df4a50b19d16e4f89e

**Comment by PremSOMISH** [comment]
Gone through your suggestions in PR #168 and responded for few comments where I needed your inputs. please go through my replies and let me know.
Fixed the code according to your suggestions where we were on same page. you can find the changes [here](https://github.com/GoodDollar/GoodContracts/commit/9670cf2293494f0a9da0677fcc97817b1a2c6897).

**Comment by PremSOMISH** [comment]
1. I have gone through your comments in PR168 and replied my thoughts. Please let me know your suggestions if any.
2. Worked on your suggestions in PR168 you can find the changes [here](https://github.com/GoodDollar/GoodContracts/commit/e588e43ba5941c106c912b378b7284e76cbdde60).
