### ISSUE TITLE
Contract for SimpleStaking

### ISSUE THREAD

**Issue by reemaSomish** [GoodDollar/GoodContracts#161]
1. - [x] Contract will inherits AbstractGoodStaking.

2. - [x] Remove specifics of DAI and cDAI and use generic names.

**Comment by PremSOMISH** [comment]
Completed changes for issue #161: "Contract for SimpleStaking" and pushed code into branch: "161-Contract-for-SimpleStaking". Let me know if something is need to be changed.

**Comment by PremSOMISH** [comment]
I have gone through your comments in PR174 and replied my thoughts. Please let me know your suggestions if any.
