### ISSUE TITLE
Create contract GoodCompoundStaking

### ISSUE THREAD

**Issue by reemaSomish** [GoodDollar/GoodContracts#162]
1. - [x] inherits SimpleStaking
2. - [x] Override staking  functions compatible to compound specific functions like mint(),redeemUnderlying() etc

**Comment by PremSOMISH** [comment]
Completed changes for issue #162: "Create contract GoodCompoundStaking" and pushed code into branch: "162-Create-contract-GoodCompoundStaking". Let me know if something is need to be changed.

**Comment by PremSOMISH** [comment]
Created PR for #162:"Create contract GoodCompoundStaking". Check PR175. Please let me know your suggestions if any.
