### ISSUE TITLE
Fix existing test cases for compund

### ISSUE THREAD

**Issue by reemaSomish** [GoodDollar/GoodContracts#163]
Fix existing test cases and make sure everything is working fine for compound.

**Comment by PremSOMISH** [comment]
1. Created new branch for #163:"Fix existing test cases for compund" , 163-Fix-existing-test-cases-for-compund. Will create PR for this issue once all changes are done.
2. Made changes in mock files and migrations and pushed into 163-Fix-existing-test-cases-for-compund.
