### ISSUE TITLE
Staking G$ interest calculation library

### ISSUE THREAD

**Issue by reemaSomish** [GoodDollar/GoodContracts#190]
1. stake+donate and unit tests
2. deposit interest + calculate staker accrued interest  + unit tests
3. withdraw accrued interest + unit tests
4. staker adds stake + unit tests

Further breakup as and when picked up.

**Comment by sirpy** [comment]
@PremSOMISH 
left todo:
- [ ] update unit tests after my refactoring
- [ ] update variables and methods documentation

**Comment by sirpy** [comment]
@PremSOMISH see previous comment. is this issue done?
