### ISSUE TITLE
Make enough to claim once per week or two

### ISSUE THREAD

**Issue by vporton** [GoodDollar/GoodContracts#207]
### Motivation
Claiming every day is a useless work for both people and computers.

### Details
Make it possible to receive maximal possible funds when claiming only once per week.

People should only prove they aren't dead once per week or two weeks. It is enough.

No need to proof of activity of user's alarm clock to claim funds.

**Comment by sirpy** [comment]
that's the current design. in the future the  DAO can upgrade and decide otherwise
