### ISSUE TITLE
I want you to move to Matic!

### ISSUE THREAD

**Issue by vporton** [GoodDollar/GoodContracts#208]
### Motivation
M+ token will support decarbonization of the planet.

M+ community is planned to be based on quadratic voting.

Quadratic voting needs anti-Sybil. I propose to use the GoodDollar private key as the identity proof for anti-Sybil!

Thus we need GoodDollar on Matic!!

We need

### Details
Make a bridge between Fuse and Matic for GoodDollar.

**Comment by vporton** [comment]
Also Matic gas is more than 5 times cheaper than Fuse gas.

**Comment by vporton** [comment]
Maybe, I am wrong: https://github.com/MPlus4Climate/MPlusToolKit/issues/3#issuecomment-706810123

**Comment by sirpy** [comment]
Using GoodDollar's identity for anti sybil is exactly what it should be used for.
the "read" permissions to the Identity contract are open for everyone, so feel free to develop solutions on top of it.
Moving to a different blockchain is not that simple, but again G$ is open source, feel free to deploy it on matic.
