### ISSUE TITLE
Reserve should be able to mint G$ based on expansion of reserve ratio

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodContracts#83]
Formula:
S = G$ supply
R = old reserve ratio
Rr1 = new reserve ratio
P=current price
G$ to mint = R/(Rr1*P) - S

Definition of Done
- anyone can calculate G$ to mint based on expansion of reserve ratio
- reserve can update reserve ratio and calculate G$ to mint
- price stays the same

**Comment by ordd** [comment]
R = Reserve Balance

**Comment by sirpy** [comment]
@ordd this is missing from reserve
1. it is in marketmaker but not in reserve
2. basically mintInterestUBI and mintExpansionUBI should be one "atomic" method that can be called by fundmanager once a day, or perhaps callable by anyone 
3. need to check if the order of minting matters
